name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancelar builds previas
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Instalar dependencias
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run cy:run
          start: npm run start
          wait-on: http://localhost:3000
        if: ${{ github.event_name == 'push' }}
      - name: Deploy Github pages
        run: npm run deploy
